### ISSUE TITLE
Should we have a new field for magnetic declination?

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#263] opened 2024-07-17 15:03 UTC
Certain lidar OEMs are putting magnetic declination as part of the metadata. Should we add that as a field?

**Comment by stephenholleran** [comment] 2024-07-18 14:32
This is a duplicate of #255 

We'll close this one as the other one has more details.

**Closed as completed by stephenholleran** 2024-07-18 14:32 UTC
Labels: question
