### ISSUE TITLE
Sensor & Sensor_Config documentation review suggestions

### ISSUE THREAD

**Issue by abohara** [IEA-Task-43/digital_wra_data_standard#3] opened 2020-07-30 17:13 UTC
- [x] Known Bug on "Sensor Properties" table. All types set to 'null'

- [x] [Sensor -> instrument_height_mm]: Suggest description include units and indicate what it is not to avoid some confusion regarding dual meaning of height e.g "This is the physical height dimension of the sensor in millimeters (and not the height above ground at which it is deployed) to..."

- [ ] [Sensor -> instrument_height_mm] : Any reason to not leaving at as a number instead of an integer ? I don't believe 'integer' is a base json data type 

- [x]  [Sensor -> is_heated] : Append to current description to clarify that it is not relevant to all sensors., " This is usually relevant for wind speed and wind vane sensors "

- [x]  [Sensor -> is_heated] : Examples: Currently, "true, for the sensor is heated" . Should read " true, if the sensor is heated " ?

- [ ]  [Sensor -> date_from] : Current description starts with "The date from when these properties are active....". Since, this table is a description of the sensor and not its configuration, suggest this be changed to "The date when the sensor was deployed."

- [ ] [Sensor -> date_to] : Suggest description be changed to "The final end date for the sensor deployment. If the sensor is in use and not decomissioned, leave as null."

- [ ] For both 'date_from' and 'date_to' : There is some ambiguity regarding whether this should refer to the actual date when the physical installation was done or when the change was visible in the data. For e.g. may be the first anemometer was deployed on 1 Jan 2020 per maintenance sheet, however, maybe your mast data starts on 3 Jan 2020. Which one should be recorded here ? Suggest we include a line indicating, these are the physical installation dates as specified in maintenance sheets.

- [x] Suggest the datetime standard be ISO 8601 (https://en.wikipedia.org/wiki/ISO_8601). The ISO naming is more recognized and a lot of languages have a clear function to read it (for e.g. both Python and Javascript have it). Also, should specify if the timezone should be part of the string. 

- [x] For all date time, specify that timezone should be entered using ISO_8601 convention (https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators). This will mean that date time without any timezone will be interpreted as local time. In the example, have some ISO date timezone example from the wiki link above.

- [x]  [Sensor -> updated_at] : There is possible timezone issue here if the document editor is not in the same timezone as the sensor. So having timezone would clear that up.

- [x] [Sensor ->  calibration]: Should not be null since it is required for WRA right ?

- [x] [Sensor -> sensor_type_id] : Should this be changed to 'sensor_type', since it is not a unique identifier which having a prefix 'id' would imply. If we have another table that is a list of sensor types, then 'sensor_type_id' would map into it. However, currently we have an enum of 'sensor strings'. 

- [x] One thing to note is there are some sensors, where one model measures multiple values. For e.g., one of the NRG sensors (i.e. one model type) measures both pressure and temperature

- [x] [sensor_config -> sensitivity] : Add a comment in the description that " It can also be recorded as a 'slope' with zero offset and the field is currently available to support existing convention." In our previous meeting, we have had discussion on how this is different from slope and I think this comment would clarify it.

- [x] Logger Slope / offset should not be null, since they are needed to get the right calibration applied for WRA

- [x] [sensor_config -> height_m] : Clarify that this is " The height in meters (above ground level) at which the sensor is deployed as documented in the logger."

- [x]  [sensor_Config -> channel]: Should this be type number ?

- [ ] [sensor_config -> date_from / date_to] : description change to " The date when the configuration was applied in the logger...."

- [ ] [sensor_config -> date_from / date_to] : Similar issues to date_from and date_to discussed above in the sensor table

**Comment by stephenholleran** [comment] 2020-07-30 20:46
I just changed the bullets to tick boxes so we can tick them off as we go. I haven't read them yet :)

**Comment by abohara** [comment] 2020-07-31 16:59
Great! That is a neat trick !

**Comment by stephenholleran** [comment] 2020-08-06 14:53
> [Sensor -> instrument_height_mm] : Any reason to not leaving at as a number instead of an integer ? I don't believe 'integer' is a base json data type

The JSON Schema has either int or number (float) as data types. 
http://json-schema.org/understanding-json-schema/reference/numeric.html#numeric
It might be overkill to restrict this attribute to an integer.

> [Sensor -> date_from] : Current description starts with "The date from when these properties are active....". Since, this table is a description of the sensor and not its configuration, suggest this be changed to "The date when the sensor was deployed."

The date_from and date_to are 'definitions' in the JSON Schema. That is, they are just written down in one place and then linked to from the places where it is used. Therefore we need to keep the text generic. Open to amending that generic text?

> [Sensor -> date_to] : Suggest description be changed to "The final end date for the sensor deployment. If the sensor is in use and not decomissioned, leave as null."

Somewhat changed but same problem as with date_from.

> For both 'date_from' and 'date_to' : There is some ambiguity regarding whether this should refer to the actual date when the physical installation was done or when the change was visible in the data. For e.g. may be the first anemometer was deployed on 1 Jan 2020 per maintenance sheet, however, maybe your mast data starts on 3 Jan 2020. Which one should be recorded here ? Suggest we include a line indicating, these are the physical installation dates as specified in maintenance sheets.

The data model should represent how the mast was setup so I would say in this case it should be the 1st Jan as you may get data for the 1st and 2nd at a later time. There are cases however where it needs to match the data as with Ammonit loggers a change in the slope and offset is only applied when the logger actually writes to the csv file. Writing to the csv file usually happens midnight for that day so a change in the slope is applied to the whole days data and not just from the point the change happened. In this case there may need to be dates for midnight the night before and then at the point when the change actually happened. Depends on if there is any valid data up to the change which most of the time there isn't as a change in sensor is usually for a faulty sensor. This is a problem with how Ammonit loggers behave and it is different to how other loggers behave. So not sure we can be any more specific with what the dates should represent.

> Suggest the datetime standard be ISO 8601

Absolutely. The RFC https://tools.ietf.org/html/rfc3339 is a subset of the ISO 86601 as far as I know and requires the 'T' between the date and time. I made an update to the text.

> For all date time, specify that timezone should be entered using ISO_8601 convention

Timezones are a disaster and I would advice not using them at all.

> [Sensor -> updated_at] : There is possible timezone issue here if the document editor is not in the same timezone as the sensor. So having timezone would clear that up.

I don't think it would but we can have a discussion about that. :)

> [Sensor -> calibration]: Should not be null since it is required for WRA right ?

Only for anemometers, if it is available, but not for temperature, logger voltage, etc.

> [Sensor -> sensor_type_id] : Should this be changed to 'sensor_type', since it is not a unique identifier which having a prefix 'id' would imply. If we have another table that is a list of sensor types, then 'sensor_type_id' would map into it. However, currently we have an enum of 'sensor strings'.

The enum of sensor types is effectively another table and so that is why there is the 'id' on the end. See the table structure where there are some but not all in there. This is one of the things that needs cleaning up in a proper relational diagram.

> One thing to note is there are some sensors, where one model measures multiple values. For e.g., one of the NRG sensors (i.e. one model type) measures both pressure and temperature

Yep, that would lead to a duplicate of the sensor in the sensor table if it is a one to many with the measurement point table. If there is a mapping between those tables then there would be no need to duplicate. It would also mean that the sensor in that sensor table, if used on another mast, could be used again and this would enable tracking of the instrument. I'll add in mapping in the relational model. It won't change the JSON Schema as the sensor is simply a child of the measurement point and will be duplicated.

> Logger Slope / offset should not be null, since they are needed to get the right calibration applied for WRA

Yes for anemometers but there are other instruments where they might not be known such as logger voltage. Or the only information provided is a csv file with column headings. I would like to have a lot less nulls in this but for the first iteration we should make it somewhat flexible so we don't annoy users.

> [sensor_Config -> channel]: Should this be type number ?

I was allowing for 'CH1' for NRGs but also in other loggers you have analog channels numbered 1 to X and counter channels also numbered 1 to X so they are distinguished by A1 or C1 which therefore needs a string.

> [sensor_config -> date_from / date_to]

As above this text needs to be generic.

**Comment by stephenholleran** [comment] 2020-08-12 18:34
Hi @abohara,

Are you happy with my answers and what I have updated?

**Comment by abohara** [comment] 2020-08-12 22:07
Thanks @stephenholleran . 

Looks good. Some minor corrections and comments below:

- [ ] Looks like you have a typo in the _'Date To_' description. In the second sentence, _"The format of this should follow"_ should be removed :  _The final end date for when these properties are active. The format of this should follow If these properties are currently active please use null. If null is not allowed please use 2100-01-01T00:00:00. The format of this date should follow ISO 8601 with the 'T' required._

- [ ] On whether, 'required' or 'optional' for calibration + logger slope & offset. If setting to 'optional', perhaps, we can update the description to reflect your exact comments ie. typicall expected for anemometers and wind vanes, but not required for the rest.

- [ ] Finally, the generated markdown does not seem to be sync'd with your latest changes. Though, perhaps you are waiting for all the changes to come in.

Thanks

**Comment by stephenholleran** [comment] 2020-08-13 13:32
>Finally, the generated markdown does not seem to be sync'd with your latest changes. Though, perhaps you are waiting for all the changes to come in.

It should be sync'd but the generated markdown process seem to only update some files. I think once we have all updates in I'll just delete the whole docs folder to force it to generate from scratch.

Thanks for the comments. I made those other changes. I'll push them once I've finished making other updates.

**Closed by stephenholleran** 2020-08-13 13:32 UTC
