### ISSUE TITLE
Retrieving main measurement points out of load_demo_schema.ipynb

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#28] opened 2020-10-31 13:29 UTC
@stephenholleran I tried to run load_demo_schema.ipynb. Everything went well until I reached the main measurement point markdown. I am running with the example schema.
![Capture](https://user-images.githubusercontent.com/19154103/97780482-fc5aa800-1b52-11eb-8159-e29403b11810.PNG)

**Comment by stephenholleran** [comment] 2020-11-04 21:57
Hi @kersting ,

I just ran it there and it worked fine.
![image](https://user-images.githubusercontent.com/25622575/98171791-37a8fe00-1ee8-11eb-90c0-55e158b0a0ad.png)

I wonder if it is finding the demo json file at all? Just type `meta_data` in a cell and see if it contains anything?
![image](https://user-images.githubusercontent.com/25622575/98171923-67580600-1ee8-11eb-83a6-210164900d88.png)

It is probably this line highlighted that is not working.
![image](https://user-images.githubusercontent.com/25622575/98172145-bef67180-1ee8-11eb-8fa7-a2cdf0a852b1.png)

**Comment by kersting** [comment] 2020-11-04 22:28
@stephenholleran That is not the problem. See the screenshot. The file is loading fine. Also, I haven't modified anything. I am working with what I cloned from GitHub.
![Capture](https://user-images.githubusercontent.com/19154103/98174593-bb4bf600-1eba-11eb-807f-81d378783f76.PNG)

**Comment by stephenholleran** [comment] 2020-11-05 14:28
Hi Gibson, I don't know. I don't know how you are running it? It doesn't look like it is in a Notebook? So I can't replicate it.

It runs in the binder Notebook through the GitHub repo. 

If sensors_table_report is a pandas dataframe then it should work. The problem is not with that line but somewhere earlier. That is why I thought the file wasn't read in correctly. I don't know how I can help if I can't replicate it.

**Comment by stephenholleran** [comment] 2020-11-09 16:46
The problem is that pandas version 1.1.4 does not have the method .contains for df.columns.

Possible solution could be:
```
     if 'date_from' == [col for col in sensors_table_report.columns if 'date_from' == col][0]:
```

**Comment by kersting** [comment] 2020-11-09 17:22
@stephenholleran thanks for looking into that. The proposed solution does not work. I'm getting another error. list index out of range

**Comment by abohara** [comment] 2021-01-29 05:52
@stephenholleran @kersting Replacing the following should do it. What we should really do is include a 'conda' environment or pip requirements file to fix the version of the packages. The following changes should make it generic enough to work though (atleast it does on my computer :\ and I was having the same issues as Gibson)

**Replace**
```
if sensors_table_report.columns.contains('date_from'):
        sensors_table_report['date_from'] = pd.to_datetime(sensors_table_report['date_from']).dt.strftime("%d-%b-%Y")
        sensors_table_report['date_to'] = pd.to_datetime(sensors_table_report['date_to']).dt.strftime("%d-%b-%Y")
```

**with** 

```
if 'date_from' in sensors_table_report.columns:
        sensors_table_report['date_from'] = pd.to_datetime(sensors_table_report['date_from'].astype(str)).dt.strftime("%d-%b-%Y")
if 'date_to' in sensors_table_report.columns:
        sensors_table_report['date_to'] = pd.to_datetime(sensors_table_report['date_to'].astype(str)).dt.strftime("%d-%b-%Y")
```

**Comment by abohara** [comment] 2021-01-29 05:52
I would submit a pull request, but I can't clone the repo currently because the file name in the docs folder are too long.

**Comment by kersting** [comment] 2021-01-31 16:28
I'm getting the same error. The file is too long for cloning as well.

**Comment by stephenholleran** [comment] 2021-01-31 18:03
@kersting 
This post might help:
https://github.com/IEA-Task-43/digital_wra_data_standard/issues/46#issuecomment-770398499

**Comment by kersting** [comment] 2021-02-01 00:29
@stephenholleran both the link you provided me for the git fix and your updated code worked. I'll submit a pull request.

**Comment by kersting** [comment] 2021-02-01 00:37
The pull request has been submitted.

**Comment by stephenholleran** [comment] 2021-02-01 10:43
@kersting that is great.

I don't see a pull request though?

**Comment by kersting** [comment] 2021-02-05 01:05
@stephenholleran Can you see if it went through. It may be proxy problem from my side.

**Comment by stephenholleran** [comment] 2021-02-05 10:01
Hi @kersting, there is a new commit direct into the master branch with the fix. There was no pull request.

I'll close this now with that fix. Thanks guys.

**Closed by stephenholleran** 2021-02-05 10:01 UTC
Labels: bug
